# Generated by Django 3.1.7 on 2021-05-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100, verbose_name='email')),
                ('user_password', models.CharField(max_length=100, verbose_name='password')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
