# Generated by Django 3.1.7 on 2021-05-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='name')),
                ('item_price', models.CharField(max_length=100, verbose_name='price')),
                ('item_type', models.CharField(max_length=100, verbose_name='type')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
