# Generated by Django 3.1.7 on 2021-05-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshop', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_img',
            field=models.CharField(default='abc', max_length=100, verbose_name='name'),
        ),
    ]
