# Generated by Django 3.1.7 on 2021-05-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshop', '0004_auto_20210502_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
    ]
