# Generated by Django 3.1.7 on 2021-05-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshop', '0005_auto_20210502_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
    ]
