# Generated by Django 3.1.7 on 2021-05-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshop', '0006_remove_orderitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_price',
            field=models.FloatField(),
        ),
    ]
